calculate_charge:
  description: Calculate when to cahrge house battery
  fields:
    charge_period:
      name: Charge period
      description: How many hours to plan charge
      required: true
      default: 3
      selector:
        select:
          options:
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
    cutoff:
      name: Price cutoff
      description: Cutoff on price
      required: true
      default: 0.5
      selector:
        select:
          options:
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
            - 0.6
            - 0.7
            - 0.8
            - 0.9