calculate_charge:
  description: Calculate when to cahrge house battery
  fields:
    car_charge_stop:
      name: Sluta ladda bil vid
      description: Sluta ladda n채r batteriet n책r antal procent
      required: true
      default: 80
      selector:
        select:
          options:
            - 70
            - 80
            - 90
            - 100
    car_charge_effect:
      name: Laaddeffect bil
      description: Laddeffekt i kw
      required: true
      default: "6.9"
      selector:
        select:
          options:
            - 6.9
            - 8.2
            - 9.9
            - 11
    house_charge_stop:
      name: Sluta ladda husbatteri vid
      description: Sluta ladda n채r batteriet n책r antal procent
      required: true
      default: 95
      selector:
        select:
          options:
            - 70
            - 80
            - 90
            - 95
            - 100            
    house_charge_effect:
      name: Laaddeffect husbatteri
      description: Laddeffekt i kw
      required: true
      default: 4
      selector:
        select:
          options:
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10            