calculate_charge:
  description: Calculate when to cahrge house battery
  fields:
    execute_actions:
      name: Execute configured charge actions
      description: Trigger configured charger services if the calculated window should start now
      required: false
      default: false
      selector:
        boolean:
    car_charge_stop:
      name: Sluta ladda bil vid
      description: Sluta ladda när batteriet når antal procent
      required: true
      default: 80
      selector:
        select:
          options:
            - 70
            - 80
            - 90
            - 100
    car_charge_effect:
      name: Laaddeffect bil
      description: Laddeffekt i kw
      required: true
      default: "6.9"
      selector:
        select:
          options:
            - 6.9
            - 8.2
            - 9.9
            - 11
    car_max_sessions:
      name: Max antal laddpass bil
      description: Dela upp laddning i flera billigare pass per dag
      required: false
      default: 1
      selector:
        select:
          options:
            - 1
            - 2
            - 3
    house_charge_stop:
      name: Sluta ladda husbatteri vid
      description: Sluta ladda när batteriet når antal procent
      required: true
      default: 95
      selector:
        select:
          options:
            - 70
            - 80
            - 90
            - 95
            - 100            
    house_charge_effect:
      name: Laaddeffect husbatteri
      description: Laddeffekt i kw
      required: true
      default: 4
      selector:
        select:
          options:
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
    house_max_sessions:
      name: Max antal laddpass husbatteri
      description: Dela upp laddning i flera billigare pass per dag
      required: false
      default: 1
      selector:
        select:
          options:
            - 1
            - 2
            - 3
